name: artefact-build-and-image-upload
on: [push]

env:
  GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

jobs:
  image-build-and-upload:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout source code'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Get image tag'
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: 'Build and push image to GCP Artefact Registry'
      run: 'gcloud builds submit --tag ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/containers/rusty_bike:${{ steps.vars.outputs.sha_short }} .'
